### ISSUE TITLE
won\\t build on Jetson 4.6 with the latest sdk

### ISSUE THREAD

**Issue by AndreV84** [adujardin/zed-save-depth#18]
```
             param.Depth_Format = static_cast<sl::DEPTH_FORMAT> (mode_Depth % 3);
                       ^~~~~~~~~~~~
/home/nvidia/zed-save-depth/src/main.cpp:331:54: error: ‘DEPTH_FORMAT’ in namespace ‘sl’ does not name a type
                 param.Depth_Format = static_cast<sl::DEPTH_FORMAT> (mode_Depth % 3);
                                                      ^~~~~~~~~~~~
/home/nvidia/zed-save-depth/src/main.cpp:332:70: error: ‘SaveParam {aka struct SaveParamStruct}’ has no member named ‘Depth_Format’
                std::cout << "Format Depth " << getFormatNameD(param.Depth_Format) << std::endl;
                                                                     ^~~~~~~~~~~~
CMakeFiles/ZED_Save_depth.dir/build.make:62: recipe for target 'CMakeFiles/ZED_Save_depth.dir/src/main.o' failed
make[2]: *** [CMakeFiles/ZED_Save_depth.dir/src/main.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ZED_Save_depth.dir/all' failed
make[1]: *** [CMakeFiles/ZED_Save_depth.dir/all] Error 2
Makefile:83: recipe for target
```
any ideas? how to save pointcloud on jetson?

**Comment by adujardin** [comment]
This sample was made for ZEDSDK 2.X, for a newer version you should refer to this sample instead https://github.com/stereolabs/zed-opencv/tree/master/cpp
You can use `sl::Mat::write` function to export a point cloud https://www.stereolabs.com/docs/api/classsl_1_1Mat.html#accab3cb8c395f6b32c897e549fef78a8

**Comment by AndreV84** [comment]
@adujardin 
Hi, I was able to save with yoru reference cpp code.
But it failed at the next step of processing the recorded xyz with open3d
the error is due to [as folks said: "It is either you don't have RGB info in your xyz  file or they are in the wrong order."]
I tried to load the xyz into open 3d then execute these
that worked
```
dataname="Cloud_526.xyz"
point_cloud= np.loadtxt(input_path+dataname,skiprows=1)
```
but the next step failed
```
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(point_cloud[:,:3])
pcd.colors = o3d.utility.Vector3dVector(point_cloud[:,3:6]/255)
pcd.normals = o3d.utility.Vector3dVector(point_cloud[:,6:9])
```
using colab https://colab.research.google.com/drive/1HXVOK53ac6BJHAFxdEVluhFr7UAZKtDV#scrollTo=Q-6ISxhQfC0s&uniqifier=1
folks said it is because  "It is either you don't have RGB info in your xyz  file or they are in the wrong order."

**Comment by AndreV84** [comment]
can zed save pointcloud as ply with vertices/ mesh?
